enyo.depends(
    "AddDialog.js",
    "AuthDialog.js",
    "ArticleListItem.js",
    "ArticleView.js",
    "LinkPopup.js",
    "PickerWithHintAndBinding.js",
    "SettingsDialog.js",
    "Spritzdialog.js",
    "views.js"
);
