enyo.depends(
    "AddDialog.js",
    "AuthDialog.js",
    "ArticleListItem.js",
    "ArticleView.js",
    "IFrameWebView.js",
    "LinkPopup.js",
    "PickerWithHintAndBinding.js",
    "SettingsDialog.js",
    "SpritzDialog.js",
    "TouchScrollStrategyWithThumbs.js",
    "views.js"
);
